import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
	GENERATED_SHADER_ROOT,
	GENERATED_SOURCE_ROOT,
	LILTOON_ROOT,
	PROJECT_ROOT,
} from "../paths.js";
import { buildVariant } from "./build-variant.js";
import { generateWebAppdata } from "./generate-web-appdata.js";
import { generateSpecialization } from "./generate-specialization.js";
import { generateFur } from "./generate-fur.js";
import { sha256 } from "./hash.js";
import { discoverToolchain, getVersion } from "./toolchain.js";
import { SHADER_VARIANTS } from "./variants.js";
import { resourceManifest } from "./resource-manifest.js";

const toolchain = discoverToolchain();
generateWebAppdata();
generateSpecialization();
generateFur();
const built = SHADER_VARIANTS.map((variant) => {
	process.stdout.write(`Building ${variant.key}...\n`);
	return buildVariant(variant, toolchain);
});
const lilToonCommit = execFileSync("git", ["rev-parse", "HEAD"], {
	cwd: LILTOON_ROOT,
	encoding: "utf8",
}).trim();
const shaderManifest = {
	lilToonCommit,
	dxcVersion: getVersion(toolchain.dxc, ["--version"]).split("\n")[0],
	spirvCrossVersion: getVersion(toolchain.spirvCross, ["--revision"]).split(
		"\n",
	)[0],
	variants: built.map((variant) => ({
		...variant,
		stages: Object.fromEntries(
			Object.entries(variant.stages).map(([stage, artifact]) => [
				stage,
				{
					...artifact,
					sha256: sha256(readFileSync(resolve(PROJECT_ROOT, artifact.glsl))),
				},
			]),
		),
	})),
};
mkdirSync(resolve(GENERATED_SHADER_ROOT, "manifests"), { recursive: true });
mkdirSync(GENERATED_SOURCE_ROOT, { recursive: true });
writeFileSync(
	resolve(GENERATED_SHADER_ROOT, "manifests/shader-manifest.json"),
	`${JSON.stringify(shaderManifest, null, 2)}\n`,
);
const shaderEntries = built
	.filter((variant) => variant.renderMode !== "smoke")
	.map((variant) => {
		const vertex = readFileSync(
			resolve(PROJECT_ROOT, variant.stages.vertex.glsl),
			"utf8",
		);
		const fragment = readFileSync(
			resolve(PROJECT_ROOT, variant.stages.fragment.glsl),
			"utf8",
		);
		const resources = [
			...resourceManifest(
				vertex,
				resolve(PROJECT_ROOT, variant.stages.vertex.reflection),
				"vertex",
			),
			...resourceManifest(
				fragment,
				resolve(PROJECT_ROOT, variant.stages.fragment.reflection),
				"fragment",
			),
		];
		return [variant.key, { vertex, fragment, resources }];
	});
writeFileSync(
	resolve(GENERATED_SOURCE_ROOT, "shaders.ts"),
	`// Generated by tools/shader-build/build-all.ts. Do not edit.\n` +
		`export interface ShaderResource { readonly uniform: string; readonly property: string; readonly sampler: string; readonly type: string; readonly stage: "vertex" | "fragment" }\n` +
		`export interface GeneratedLilToonShader { readonly vertex: string; readonly fragment: string; readonly resources: readonly ShaderResource[] }\n` +
		`export const LILTOON_SHADERS: Readonly<Record<string, GeneratedLilToonShader>> = ${JSON.stringify(Object.fromEntries(shaderEntries), null, 2)};\n`,
);
writeFileSync(
	resolve(GENERATED_SOURCE_ROOT, "shaderManifest.ts"),
	`// Generated by tools/shader-build/build-all.ts. Do not edit.\nexport const LILTOON_SHADER_MANIFEST = ${JSON.stringify(shaderManifest, null, 2)} as const;\n`,
);
process.stdout.write(`Built and validated ${built.length} shader variants.\n`);
